- appgate/resource_appgate_condition.go
- appgate/resource_appgate_condition_test.go
- appgate/resource_appgate_criteria_script.go
- appgate/resource_appgate_entitlement.go
- appgate/resource_appgate_entitlement_test.go
- appgate/resource_appgate_policy.go
- appgate/resource_appgate_policy_test.go
- appgate/resource_appgate_ringfence_rule.go
- appgate/resource_appgate_ringfence_rule_test.go
correctly read all attributes for resources:
- entitlement
- condition
- criteria script
- policy
- ringfence rule
previous this was missing, which caused incomplete state in the statefile. This will improve usage when running terraform import on these resources,
> Complex read

- appgate/resource_appgate_condition.go
- appgate/resource_appgate_condition_test.go
- examples/main.tf
fields claimSuffix and providerId is only required when type != DisplayMessage.
> support condition with remedy action displayMessage

- appgate/data_source_appgate_entitlement_script.go
- appgate/provider.go
- appgate/resource_appgate_device_script.go
- appgate/resource_appgate_device_script_test.go
- examples/main.tf
- website/docs/r/device_script.markdown
new resource, appgate device script  
example: 
```hcl
resource "appgate_device_script" "example_device_script" {
name     = "device_script_name"
filename = "script.sh"
content  = <<-EOF
#!/usr/bin/env bash
echo "hello world"
EOF
tags = [
"terraform",
"api-created"
]
}
```
> Resource device script

- appgate/config.go
- appgate/provider.go
- website/docs/index.html.markdown
toggle HTTP request/response in debug mode.
Usage:
```
export TF_LOG=DEBUG
export APPGATE_HTTP_DEBUG=true
```
> env variable APPGATE_HTTP_DEBUG

- appgate/identity_provider.go
- appgate/resource_appgate_identity_provider_saml.go
- appgate/resource_appgate_identity_provider_saml_test.go
Good Evening!
Few fixes:
- While using the saml idp resource, we noticed that if you changed the order of the claims (claim mapping or on-demand), TF would complain and try to update things... This is not good. Based on the API docs, these are arrays and doesn't specify that order maters. As such, the majority of the changes to the idp and saml idp files were related to changing the claims from "TypeList" to "TypeSet" so order would no longer matter. 
- We found a bug while testing "claim mappings" where the "encrypted" field wasn't being sent to the api or read back in right. 
Additionally, I enhanced the test file for SAML IDP so it is a bit more robust, testing creation, updates, and deletes. 
Let me know if there are any questions/comments you need me to address. 
Thank you,
Derek
> Saml idp bug fix

- appgate/resource_appgate_entitlement.go
- appgate/resource_appgate_entitlement_test.go
Resolved issue while trying to updated entitlement, this PR fixes #96 
acceptance test
<details>
```
make testacc
=== RUN   TestGetToken200
--- PASS: TestGetToken200 (0.00s)
=== RUN   TestAccAppgateApplianceCustomizationDataSource
=== PAUSE TestAccAppgateApplianceCustomizationDataSource
=== RUN   TestAccAppgateApplianceSeedDataSource
--- PASS: TestAccAppgateApplianceSeedDataSource (13.30s)
=== RUN …
```
> Update entitlements 96

- README.md
- go.mod
- main.go
this fixes #101 , we recently changed the name of the github repository but not the go mod name reference.
> updated go mod name

- Makefile
- appgate/hashcode/hashcode.go
- appgate/hashcode/hashcode_test.go
- appgate/resource_appgate_entitlement.go
- appgate/resource_appgate_entitlement_test.go
- appgate/util.go
Updated Entitlement.actions from TypeList to TypeSet
this solves, #98
acceptance test result
<details>
```
> make testacc
=== RUN   TestGetToken200
--- PASS: TestGetToken200 (0.01s)
=== RUN   TestAccAppgateApplianceCustomizationDataSource
=== PAUSE TestAccAppgateApplianceCustomizationDataSource
=== RUN   TestAccAppgateApplianceSeedDataSource
--- PASS: TestAccAppgateApplianceSeedDataSource (15.06s)
=== RUN …
```
> Entitlement.actions from TypeList to TypeSet

- Makefile
- appgate/resource_appgate_appliance.go
- appgate/resource_appgate_appliance_test.go
- appgate/util.go
Based on the discussion in https://github.com/appgate/terraform-provider-appgatesdp/issues/117 , allow `override_spa_mode` as Disabled in tf state, even though the API does not accept it anymore.
Tested on `5.3.2-23587-release`
```
make testacc
--- PASS: TestLoginInternalServerError (0.01s)
--- PASS: TestConfig (0.00s)
=== RUN   TestAccAppgateApplianceCustomizationDataSource
=== PAUSE TestAccAppgateApplianceCustomizationDataSource
=== RUN …
```
> Override spa mode disabled

- appgate/resource_appgate_site.go
- appgate/resource_appgate_site_test.go
This partially fixes https://github.com/appgate/terraform-provider-appgatesdp/issues/122
acceptance test result for 5.3.2-23587-release
```
make testacc
--- PASS: TestLoginInternalServerError (0.01s)
--- PASS: TestConfig (0.00s)
=== RUN   TestAccAppgateApplianceCustomizationDataSource
=== PAUSE TestAccAppgateApplianceCustomizationDataSource
=== RUN   TestAccAppgateApplianceSeedDataSource
--- PASS: TestAccAppgateApplianceSeedDataSource (9.79s)
=== …
```
> site.name_resolvers.aws_resolver withouut secret_access_key

- appgate/provider.go
- appgate/resource_appgate_client_connections.go
- appgate/resource_appgate_client_profile.go
- appgate/resource_appgate_client_profile_test.go
- appgate/util.go
- go.mod
- go.sum
- website/docs/r/client_connections.markdown
- website/docs/r/client_profile.markdown
New resource `appgatesdp_client_profile`, this will replace `appgatesdp_client_connections`. This for easier handling the  state and control CRUD operations of Client Profiles. This will mitigate errors seen in https://github.com/appgate/terraform-provider-appgatesdp/issues/123
acceptance test on 5.`3.2-23587-release`
```
make testacc
--- PASS: TestConfig (0.01s)
=== RUN …
```
> Client profile resource

- appgate/resource_appgate_administrative_role.go
- appgate/resource_appgate_administrative_role_test.go
Remove validation in the terraform provider for `privileges.target` and `privileges.type` and rely on server side validation instead. added regression test for https://github.com/appgate/terraform-provider-appgatesdp/issues/129#issuecomment-852211335
in 5.2, `OnBoardedDevice` is a valid target, and in 5.3 and above its called `RegisteredDevice`
administrative role acceptance test on 5.2.4-24406-release
```bash
TF_ACC=1 \                      
go test -v -timeout 120m github.com/appgate/terraform-provider-appgatesdp/appgate -run '^(TestAccadministrativeMultiplePrivileges*.+)$'
=== RUN   TestAccadministrativeMultiplePrivilegesValidation
=== PAUSE TestAccadministrativeMultiplePrivilegesValidation
=== RUN   TestAccadministrativeMultiplePrivilegesValidation52
=== PAUSE …
```
> Admin role 129

- appgate/resource_appgate_site.go
- appgate/resource_appgate_site_test.go
fixed missing update check, this PR resolves #138 
<details>
tested on appliance 5.3.2-23587-release
```bash
> terraform version                                                                  
Terraform v1.0.2
on linux_amd64
> make testacc
=== RUN   TestConfig/test_before_5.4
=== RUN   TestConfig/test_5.4_login
=== RUN   TestConfig/invalid_client_version
--- PASS: TestConfig (0.00s)
--- PASS: TestConfig/test_before_5.4 (0.00s)
--- PASS: TestConfig/test_5.4_login (0.00s)
--- PASS: …
```
> updated site short_name

- Makefile
- appgate/data_source_appgate_entitlement.go
- appgate/data_source_appgate_entitlement_test.go
This fixes  #141, resolve Entitlement based on exact name match.
Patches:
- replace Schema.Read() witht Schema.ReadContext, since Read() is marked as deprecated.
- added missing acceptance test for data source.
- corrected state attribute name to entitlement_name
- set entitlement_id in state.
> Entitlement data source 141

- Makefile
- appgate/resource_appgate_global_settings.go
- appgate/resource_appgate_global_settings_test.go
- website/docs/r/global_settings.markdown
include profile dns name in global settings resource ( 5.4)
patches:
replaced old schema CRUD functions with context support.
> Profile DNS Name (used when exporting client profiles)

- appgate/resource_appgate_appliance.go
- appgate/resource_appgate_appliance_test.go
resource appliance correctly read from remote. Before, it only compared to existing attributes in the statefile instead of comparing to remote.
the following attributes were affected by this
site
customization
ntp
ssh_server
snmp_server
healthcheck_server
prometheus_exporter
ping
log_server
controller
gateway
log_forwarder
connector
this fixes #144
<details>
acceptance test result for 5.4.1-25150-release
```bash
> make testacc
=== RUN   TestConfig/test_before_5.4
=== RUN   TestConfig/test_5.4_login
=== …
```
> resource appliance correctly read from remote. 

- Makefile
- appgate/resource_appgate_appliance.go
This PR fixes https://github.com/appgate/terraform-provider-appgatesdp/issues/147
<details>
tested on 5.4.1-25150-release
```
> make testacc
=== RUN   TestConfig/test_before_5.4
=== RUN   TestConfig/test_5.4_login
=== RUN   TestConfig/invalid_client_version
--- PASS: TestConfig (0.01s)
--- PASS: TestConfig/test_before_5.4 (0.00s)
--- PASS: TestConfig/test_5.4_login (0.00s)
--- PASS: TestConfig/invalid_client_version (0.00s)
=== PAUSE …
```
> Issue/147 - appliance.customization computed attribute.

- appgate/data_source_appgate_appliance_seed.go
- appgate/resource_appgate_administrative_role.go
- appgate/resource_appgate_appliance.go
- appgate/resource_appgate_appliance_customization.go
- appgate/resource_appgate_condition.go
- appgate/resource_appgate_criteria_script.go
- appgate/resource_appgate_device_script.go
- appgate/resource_appgate_entitlement.go
- appgate/resource_appgate_entitlement_script.go
- appgate/resource_appgate_global_settings.go
- appgate/resource_appgate_identity_provider_ldap.go
- appgate/resource_appgate_identity_provider_ldap_certificate.go
- appgate/resource_appgate_ip_pool.go
- appgate/resource_appgate_mfa_provider.go
- appgate/resource_appgate_site.go
- appgate/resource_appgate_trusted_certificate.go
This PR adds checks for resources in case they are manually deleted, and thus not in sync with the state. These checks will remove manually removed resources from the state when they are not found.
Fixes: #152
> Add check for resource not found all around

- appgate/resource_appgate_appliance.go
- appgate/resource_appgate_appliance_test.go
- appgate/resource_appgate_criteria_script_test.go
Correctly remove admin_interface if has been removed from the state, dont sent empty json stub of admin_interface if it has been removed, This PR solved issue #153 
Acceptance test on 5.3.2-23587-release
<details>
```
> make testacc
=== RUN   TestConfigGetToken
=== RUN   TestConfigGetToken/test_before_5.4
=== RUN   TestConfigGetToken/test_5.4_login
=== RUN   TestConfigGetToken/invalid_client_version
--- PASS: TestConfigGetToken (0.00s)
--- PASS: TestConfigGetToken/test_before_5.4 (0.00s)
--- PASS: …
```
> appliance.admin_interface remove correctly

- Makefile
- appgate/config.go
- appgate/config_test.go
- go.mod
- go.sum
Add support for retryable login, to retry if we get HTTP 5XX response.
Acceptance test on 5.4.1-25150-release
<details>
```bash
make testacc
=== RUN   TestConfigGetToken
=== RUN   TestConfigGetToken/test_before_5.4
2021/09/22 09:35:31 [DEBUG] Login OK
=== RUN   TestConfigGetToken/test_5.4_login
2021/09/22 09:35:31 [DEBUG] Login OK
=== RUN   TestConfigGetToken/invalid_client_version
2021/09/22 09:35:31 [DEBUG] Login OK
=== RUN   TestConfigGetToken/500_login_response
2021/09/22 09:35:31 [DEBUG] Login failed, controller not …
```
> Retryable login with exponential backoff

- appgate/data_source_appgate_condition.go
I came across this data source which does not expose argument condition_id as an attribute which is supposed to be used by other resource which leaves developers to use `.id` which is terraform id 
this also matches with other data sources example https://github.com/appgate/terraform-provider-appgatesdp/blob/master/appgate/data_source_appgate_site.go#L86
```
│ Error: Null value found in list
│
│   with appgatesdp_entitlement.map["ssh"],
│   on appgate.tf line 382, in resource "appgatesdp_entitlement" "map":
│  382:   conditions = [
│  383:     data.appgatesdp_condition.check_falcon.condition_id,
│  384:   ]
│
│ Null values are not allowed for this attribute value.
```
> appgate_condition: expose condition_id as attribute

- appgate/resource_appgate_appliance.go
- website/docs/r/appliance.markdown
Suppress `appliance.peer_interface` warning about deprecation since it wont be removed until 1-2 versions from now, will re-introduce it again in the future. Since this field is still required on all supported versions we wont show this warning until its needed.
Example of warning
```bash
│ Warning: Argument is deprecated
│ 
│   with appgatesdp_appliance.template_gateway,
│   on main.tf line 28, in resource "appgatesdp_appliance" "template_gateway":
│   28: resource "appgatesdp_appliance" "template_gateway" {
│ 
│ peer_interface is deprecated as of 5.4. All connections will be handled by clientInterface and adminInterface in the future. The hostname field is used as identifier and will take over the hostname field in the root of Appliance when this interface is removed.
│ 
│ (and 3 more …
```
> updated documentation for appliance peer_interface

- appgate/config.go
- appgate/config_test.go
- appgate/provider.go
- go.mod
- go.sum
- website/docs/index.html.markdown
This PR include improvement for configuration of the provider.
- This PR resolves merge issues seen in #185 , where the config file values was not included if default values was used.
- Changed default value of `insecure` / `APPGATE_INSECURE`, before the default value was `true`, but has now been updated to `false` as default. Since we want to tls verification on by default, and if you want to disable tls verification, you need to explicit set it to `false`.
- Updated error messages
- Updated error message when using invalid peer version for your appgate sdp collective
- Updated error message if you are trying to access the API with un-trusted tls certificate.  
- All provider attributes are now Optional in the schema, however we validate the input and make sure we have minimum required …
> Provider configuration updates

- Makefile
- appgate/appliance_schemas.go
- appgate/config.go
- appgate/config_test.go
- appgate/provider.go
- appgate/resource_appgate_appliance.go
- appgate/resource_appgate_appliance_controller.go
- appgate/util.go
- website/docs/guides/ha_controllers.markdown
- website/docs/r/appgatesdp_appliance_controller_activation.markdown
New resource,  `appgatesdp_appliance_controller_activation`. This will allow us to enable controller functionallity on a pre-existing, seeded appliance instance.
While reviewing, start with reading the `*.markdown` files before the code for extra context.
Acceptance tests has been omitted since we have not yet created the required testing infrastructure for this, however I've thoroughly tested this manually, and created an example usage here: 
- https://github.com/appgate/sdp-tf-reference-architecture/tree/high-availability-controllers/deployment/aws/high-availability-controllers
This PR will solve the problems explained in https://github.com/appgate/terraform-provider-appgatesdp/issues/188
acceptance test on 5.4.2-25749-release
<details>
```bash
> make testacc
==> Checking that code …
```
> Controller resource, support Controller in HA

- Makefile
- appgate/resource_appgate_appliance_controller.go
Include full error message body to user, in the example below, an validation error occurred during create and prompted error message `Error: 422 `, now it includes the full error message.
Before:
```
appgatesdp_appliance_controller_activation.activate_second_controller: Creating...
╷
│ Error: 422 
│ 
│   with appgatesdp_appliance_controller_activation.activate_second_controller,
│   on main.tf line 13, in resource "appgatesdp_appliance_controller_activation" "activate_second_controller":
│   13: resource "appgatesdp_appliance_controller_activation" "activate_second_controller" {
│ 
╵
```
After:
```
appgatesdp_appliance_controller_activation.activate_second_controller: Creating...
╷
│ Error: Validation error Validation failed. 
│  adminInterface.hostname is not a valid FQDN or IP address. …
```
> Improved error message ctrl activate

- appgate/config.go
Tested with [mitmproxy](https://mitmproxy.org/) on localhost, works fine. Configurable only with environment variable `HTTP_PROXY` since I dont think this should be include in the default provider configuration, but I am open for suggestions.
Example Usage:
`HTTP_PROXY="http://proxyIp:proxyPort"`
> Http proxy for the client

- appgate/config.go
- appgate/provider.go
- go.mod
- go.sum
- website/docs/index.html.markdown
new optional provider attribute, `device_id`
Usage:
```hcl
provider "appgatesdp" {
device_id = "ba20c1a2-b903-4b84-b6f1-2962c1460672" 
}
```
if `device_id` is not set, fallback to /etc/machine-id in a UUID format
> fixed device_id instead of random each time

- Makefile
- appgate/resource_appgate_site.go
- appgate/resource_appgate_site_test.go
This PR resolves the issue reported in #204 
Before it sent empty string ` "ipv6": ""` , this has now been resolved
Example payload of the request body before this PR based on the HCL config in #204 
```json
{
"defaultGateway": {
"enabledV4": true,
"enabledV6": false
},
"description": "",
"entitlementBasedRouting": false,
"id": "0a11985c-a81a-4585-abc0-b8aefdea5e08",
"name": "default test",
"notes": "Managed by terraform",
"shortName": "DT",
"tags": [
"api-created",
"default_test",
"terraform"
],
"vpn": {
"dtls": {
"enabled": false
},
"ipAccessLogIntervalSeconds": 120,
"routeVia": {
"ipv4": "10.10.10.10",
"ipv6": ""
},
"snat": false,
"stateSharing": false,
"tls": {
"enabled": true
}
}
}
```
Acceptance test for 5.3.4-24950
<details>
```bash
> make testacc
==> Checking that code complies …
```
> Issue 204 - CRUD fix for site.vpn.RouteVia

- appgate/resource_appgate_appliance.go
- appgate/resource_appgate_appliance_test.go
This PR addresses issues reported in #207  and #208 
Acceptance tests for 5.4.2-25749-release
<details>
```sh
make testacc
2022/02/07 10:24:48 [DEBUG] Login OK
2022/02/07 10:24:48 [DEBUG] Login OK
2022/02/07 10:24:48 [DEBUG] Login failed, controller not responding, got HTTP 500
2022/02/07 10:24:49 [DEBUG] Login failed, controller not responding, got …
```
> Resolve issue in appliance network configuration

- appgate/resource_appgate_policy.go
- appgate/resource_appgate_policy_test.go
This PR resolves issue #211
suppressMissingOptionalConfigurationBlock conflicts with custom Set hash value. 
Acceptance test for 5.5.4-27454-release
<details>
```sh
make testacc
2022/02/21 09:31:57 [DEBUG] Login OK
2022/02/21 09:31:57 [DEBUG] Login OK
2022/02/21 09:31:57 [DEBUG] Login failed, controller not responding, got HTTP 500
2022/02/21 09:31:58 …
```
> Appgatesdp policy/dns settings

- appgate/resource_appgate_site.go
- appgate/resource_appgate_site_test.go
This PR fixes #214 
Acceptance test for 5.5.4-27454-release
<details>
```sh
> make testacc
2022/02/21 14:31:12 [DEBUG] Login OK
2022/02/21 14:31:12 [DEBUG] Login OK
2022/02/21 14:31:12 [DEBUG] Login failed, controller not responding, got HTTP 500
2022/02/21 14:31:13 [DEBUG] Login failed, controller not responding, got HTTP 500
=== RUN …
```
> Dns forwarding allow destinations no limit

- appgate/resource_appgate_appliance.go
- appgate/resource_appgate_appliance_test.go
This PR resolve issue reported in #212 
allow `0` as netmask
Acceptance test for 5.5.4-27454-release
<details>
```sh
> make testacc
2022/03/02 14:31:43 [DEBUG] Login OK
2022/03/02 14:31:43 [DEBUG] Login OK
2022/03/02 14:31:43 [DEBUG] Login failed, controller not responding, got HTTP 500
2022/03/02 14:31:44 [DEBUG] Login failed, controller not …
```
> Issue 212 netmask

- appgate/resource_appgate_site.go
- appgate/resource_appgate_site_test.go
This PR resolves #229 where we could not send `resolve_with_master_credentials=false`  in the request.
> Issue 229/resolve with master credentials

- appgate/identity_provider.go
- appgate/resource_appgate_identity_provider_ldap_certificate.go
- appgate/resource_appgate_identity_provider_local_database.go
- appgate/resource_appgate_identity_provider_radius.go
- appgate/resource_appgate_identity_provider_saml.go
- appgate/resource_appgate_identity_provider_saml_test.go
add missing attribute, user_scripts to identity_providers this fixes #246
Acceptance tests for 5.5.6-29089-release
<details>
```
make testacc
2022/08/09 16:58:15 [DEBUG] Login OK
2022/08/09 16:58:15 [DEBUG] Login OK
2022/08/09 16:58:15 [DEBUG] Login failed, controller not responding, got HTTP 500
2022/08/09 16:58:16 [DEBUG] Login failed, controller …
```
> add missing attribute, user_scripts to identity_providers

- website/docs/guides/version_compatibility.markdown
version = "0.9.0"   resulted in the following error on "terraform init" since that version does not exist on registry.terraform.io
Initializing provider plugins...
- Finding appgate/appgatesdp versions matching "0.9.0"... ╷
│ Error: Failed to query available provider packages │
│ Could not retrieve the list of available versions for provider appgate/appgatesdp: no available releases match the given constraints 0.9.0
> bumped version to 1.0.1 since 0.9.0 does not exist

- appgate/resource_appgate_appliance_controller.go
- appgate/util.go
This PR includes some internal improvements when creating, updating, and deleting `appgatesdp_appliance_controller_activation` 
to avoid getting in a false negative state as shown in #258 
The practitioner will only be prompted with a warning message if the appliance state check fails or exceed timeout during destroy. It's no longer a fatal error.
This PR also includes some maintenance work, such as:
- replace deprecated function Retry() with RetryContext()
- Updated debug logs
- extended usage of [diags](https://www.terraform.io/plugin/framework/diagnostics)
- Updated default timeout values from 15 to 45 minutes for create,update, and delete.
> appliance controller activation revisited

- appgate/identity_provider.go
- appgate/resource_appgate_identity_provider_ldap.go
- appgate/resource_appgate_identity_provider_ldap_certificate.go
- appgate/resource_appgate_identity_provider_local_database.go
- appgate/resource_appgate_identity_provider_radius.go
- appgate/resource_appgate_identity_provider_saml.go
- appgate/resource_appgate_identity_provider_saml_test.go
- go.mod
- go.sum
- website/docs/r/connector_identity_provider.markdown
- website/docs/r/ldap_certificate_identity_provider.markdown
- website/docs/r/ldap_identity_provider.markdown
- website/docs/r/local_database_identity_provider.markdown
- website/docs/r/radius_identity_provider.markdown
- website/docs/r/saml_identity_provider.markdown
Updated identity provider resource to include missing attribute `network_inactivity_timeout_enabled` that was introduced in 6.1. This PR fixes #274 
Depends on:  https://github.com/appgate/sdp-api-client-go/pull/20
- updated the docs, some of the identity providers docs was out-of-date.
> identity providers network_inactivity_timeout_enabled

- appgate/resource_appgate_appliance.go
`appliance.hostname` is here to stay. There was plans before to remove it, but we still need it for the foreseeable future.
> removed appliance.hostname deprecation notice

- appgate/resource_appgate_license.go
this commit resolve #94 and when trying to use `terraform import`
Correctly use each license UUID instead of requestCode as identifier.
This has been tested manually on controller `5.4`, `5.5`, `6.0`, `6.1`.
> use license UUID as identitifer

- appgate/resource_appgate_client_profile.go
- appgate/resource_appgate_client_profile_test.go
the `url` attribute was removed in the default endpoint  `/admin/client-profiles/{ID}` in 6.1 and moved to a separate endpoint `admin/client-profiles/{ID}/url`
This PR make sure we still get the url attribute on `appgatesdp_client_profile` resource.
This PR fixes #288
> client profile url attribute

- appgate/resource_appgate_appliance.go
- appgate/resource_appgate_appliance_test.go
resolve appliance.gateway.vpn.allow_destinations address/netmask set
set only netmask if a address is set.
This commit fixes https://github.com/appgate/terraform-provider-appgatesdp/issues/304
> Set only netmask if address is set.

- appgate/resource_appgate_policy.go
- appgate/resource_appgate_policy_test.go
This PR resolves #308
DiffSuppressFunc is no longer needed on any supported versions of appgatesdp for policy
> #308/entitlement list

- appgate/resource_appgate_appliance.go
- appgate/resource_appgate_appliance_test.go
Some fields for `appliance.prometheus_exporter` had the wrong version checking code
> basic_auth, allowed_users, use_https, and https_p12  for appliance.prometheusExporter are only available since 6.2

- appgate/resource_appgate_site.go
- appgate/resource_appgate_site_test.go
* Add explicit check for empty string on `site.name_resolution.dns_forwarding.site_ipv4/v6`
* Throw error if neither site_ipv4 or site_ipv6 is provided in sites.name_resolution.dns_forwarding
> Fix error on "nameResolution.dnsForwarding.siteIpv4/siteIpv6 is not a valid IP address."

- Makefile
- appgate/resource_appgate_identity_provider_connector.go
- appgate/resource_appgate_identity_provider_ldap.go
- appgate/resource_appgate_identity_provider_ldap_certificate.go
- appgate/resource_appgate_identity_provider_local_database.go
- appgate/resource_appgate_identity_provider_oidc.go
- appgate/resource_appgate_identity_provider_radius.go
When fetching the config, we should be converting the data into schema.Set, not []interface{}
```
appgatesdp_oidc_identity_provider.oidc: Modifying... [id=bbb86809-4c41-43f3-a1cb-1927825b478f]
╷
│ Error: Plugin did not respond
│
│   with appgatesdp_oidc_identity_provider.oidc,
│   on main.tf line 46, in resource "appgatesdp_oidc_identity_provider" "oidc":
│   46: resource "appgatesdp_oidc_identity_provider" "oidc" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
Stack trace from the terraform-provider-appgatesdp_v9.9.9 plugin:
panic: interface conversion: interface {} is *schema.Set, not []interface {}
goroutine 23 [running]: …
```
> Wrong data type used for appgatesdp_oidc_identity_provider.claim_mappings

- Makefile
- appgate/resource_appgate_blacklist_user_test.go
- appgate/resource_appgate_identity_provider_connector.go
- appgate/resource_appgate_identity_provider_ldap.go
- appgate/resource_appgate_identity_provider_ldap_certificate.go
- appgate/resource_appgate_identity_provider_local_database.go
- appgate/resource_appgate_identity_provider_oidc.go
- appgate/resource_appgate_identity_provider_radius.go
Fix for #375 
When fetching the config, we should be converting the data into `schema.Set`, not `[]interface{}`
```
appgatesdp_oidc_identity_provider.oidc: Modifying... [id=bbb86809-4c41-43f3-a1cb-1927825b478f]
╷
│ Error: Plugin did not respond
│
│   with appgatesdp_oidc_identity_provider.oidc,
│   on main.tf line 46, in resource "appgatesdp_oidc_identity_provider" "oidc":
│   46: resource "appgatesdp_oidc_identity_provider" "oidc" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
Stack trace from the terraform-provider-appgatesdp_v9.9.9 plugin:
panic: interface conversion: interface {} is *schema.Set, not []interface {}
goroutine 23 [running]: …
```
> Wrong data type used for `appgatesdp_oidc_identity_provider.claim_mappings`
