- website/docs/r/appliance.markdown
- website/docs/r/condition.markdown
- website/docs/r/entitlement.markdown
- website/docs/r/policy.markdown
- website/docs/r/ringfence-rule.markdown
- website/docs/r/site.markdown
Generated boilerplate documentation based on the openAPI specification, and added examples. these resource will later be used with https://github.com/hashicorp/terraform-website
> website resource documentation

- appgate/resource_appgate_site.go
- appgate/resource_appgate_site_test.go
- examples/site.tf
Updated `appgate_site` with all attributes, prior to this PR, only the mandatory fields were set.
> Site revisited

- appgate/resource_appgate_appliance.go
- appgate/resource_appgate_appliance_test.go
omit keys, "key_type", "key" if their values are empty.
> appliance ntp server, omit empty values.

- appgate/resource_appgate_appliance.go
- appgate/resource_appgate_appliance_test.go
- Updated indentation on test stub, to match terraform fmt.
- Updated testcase with 2 nics.
- Corrected bug from copypaste  error on ipv4  dhcp routers, and ntp.
>  corrected appliance ipv4 dhcp configuration.

- README.md
- website/docs/d/appliance.html.markdown
- website/docs/d/condition.html.markdown
- website/docs/d/entitlement.html.markdown
- website/docs/d/policy.html.markdown
- website/docs/d/ringfence-rule.html.markdown
- website/docs/d/site.html.markdown
- website/docs/index.html.markdown
- Updated documentation in README
- Added documentation for existing data sources
- Added documentation for provider attributes.
> Updated documentation

- README.md
- appgate/resource_appgate_appliance.go
- appgate/resource_appgate_appliance_test.go
- examples/main.tf
- Added configuration support for appliance ipv4 static.
- Added configuration support for appliance ipv6 dhcp/static.
> Appliance ipv6

- appgate/data_source_appgate_entitlement.go
- appgate/provider.go
get entitlement with id or name.
Forgot to add this data source before.
> data source entitlement

- appgate/data_source_appgate_device_script.go
- appgate/provider.go
- website/docs/d/device_script.html.markdown
data source for device script.
example
```hcl
variable "device_script_id" {}
data "appgate_device_script" "default_device_script" {
device_script_id = "${var.device_script_id}"
}
```
> data source device script.

- appgate/resource_appgate_appliance.go
- appgate/resource_appgate_appliance_test.go
- appgate/util.go
- examples/main.tf
Correctly read all nested attributes of the appliance, (networking,client_interface, admin_interface etcetra) this will allow us to correctly import existing site resource to the state.
> Appliance read

- appgate/data_source_appgate_administrative_role.go
- appgate/data_source_appgate_administrative_role_test.go
- appgate/provider.go
- appgate/resource_appgate_administrative_role.go
- appgate/resource_appgate_administrative_role_test.go
- website/docs/d/administrative_role.html.markdown
- website/docs/r/administrative_role.markdown
new resource and data source `appgate_administrative_role` Fixes #28
> Administrative role

- appgate/data_source_appgate_global_settings.go
- appgate/data_source_appgate_global_settings_test.go
- appgate/provider.go
- appgate/resource_appgate_global_settings.go
- appgate/resource_appgate_global_settings_test.go
- website/docs/d/global_settings.html.markdown
- website/docs/r/global_settings.markdown
Fixes #32 allow us to update global settings for the collective.
> Appgate global setting

- .gitignore
- .goreleaser.yml
- Makefile
reference:
https://www.terraform.io/docs/registry/providers/publishing.html#using-goreleaser-locally
> go releaser locally built.

- appgate/data_source_appgate_trusted_certificate.go
- appgate/data_source_appgate_trusted_certificate_test.go
- appgate/provider.go
- appgate/resource_appgate_trusted_certificate.go
- appgate/resource_appgate_trusted_certificate_test.go
- website/docs/d/trusted_certificate.html.markdown
- website/docs/r/trusted_certificate.markdown
Create new data source and resource for trusted_certificate, solves #38
> Trusted certificate

- appgate/data_source_appgate_mfa_provider.go
- appgate/data_source_appgate_mfa_provider_test.go
- appgate/provider.go
- appgate/resource_appgate_mfa_provider.go
- appgate/resource_appgate_mfa_provider_test.go
- website/docs/d/mfa_provider.html.markdown
- website/docs/r/mfa_provider.markdown
Create new data source and resource for mfa_provider, solves #37
> Mfa provider

- appgate/data_source_appgate_local_user.go
- appgate/data_source_appgate_local_user_test.go
- appgate/provider.go
- appgate/resource_appgate_local_user.go
- appgate/resource_appgate_local_user_test.go
- website/docs/d/local_user.html.markdown
- website/docs/r/local_user.markdown
New resource and data source for local user, Fixes #36
> Local user

- appgate/data_source_appgate_identity_provider.go
- appgate/data_source_appgate_identity_provider_test.go
- appgate/provider.go
- website/docs/d/identity_provider.markdown
data source for all identity providers, part of #33
> data source identity provider

- appgate/provider.go
- appgate/resource_appgate_mfa_setting.go
- appgate/resource_appgate_mfa_setting_test.go
- website/docs/r/admin_mfa_settings.markdown
New resource, admin mfa settings, Fixes #27
> Mfa setting

- appgate/provider.go
- appgate/resource_appgate_client_connections.go
- appgate/resource_appgate_client_connections_test.go
- website/docs/r/client_connections.markdown
New resource, client connections - Fixes #31
> client connection resource.

- Makefile
- appgate/data_source_appgate_administrative_role_test.go
- appgate/data_source_appgate_appliance_customization_test.go
- appgate/data_source_appgate_global_settings_test.go
- appgate/data_source_appgate_identity_provider_test.go
- appgate/data_source_appgate_ip_pool_test.go
- appgate/data_source_appgate_local_user_test.go
- appgate/data_source_appgate_mfa_provider_test.go
- appgate/data_source_appgate_trusted_certificate_test.go
- appgate/provider_test.go
- appgate/resource_appgate_administrative_role_test.go
- appgate/resource_appgate_appliance_customization_test.go
- appgate/resource_appgate_appliance_test.go
- appgate/resource_appgate_blacklist_user_test.go
- appgate/resource_appgate_client_connections_test.go
- appgate/resource_appgate_condition_test.go
- appgate/resource_appgate_criteria_script_test.go
- appgate/resource_appgate_device_script_test.go
- appgate/resource_appgate_entitlement_script_test.go
- appgate/resource_appgate_entitlement_test.go
- appgate/resource_appgate_global_settings_test.go
- appgate/resource_appgate_identity_provider_ldap_test.go
- appgate/resource_appgate_ip_pool_test.go
- appgate/resource_appgate_local_user_test.go
- appgate/resource_appgate_mfa_provider_test.go
- appgate/resource_appgate_mfa_setting_test.go
- appgate/resource_appgate_policy_test.go
- appgate/resource_appgate_ringfence_rule_test.go
- appgate/resource_appgate_site_test.go
- appgate/resource_appgate_trusted_certificate_test.go
Run acceptance test in parallel, added unique names on test resources.
> acceptance test in pararell.

- appgate/resource_appgate_appliance_test.go
> Use proper subnet in acceptance test.

- appgate/resource_appgate_appliance.go
- appgate/resource_appgate_appliance_test.go
Addresses #74 and #75 
Also, enhanced the testing performed on appliance controllers.
> Fix appliance update issues

- appgate/data_source_appgate_certificate_authority.go
- appgate/data_source_appgate_certificate_authority_test.go
- appgate/provider.go
- website/docs/d/certificate_authority.markdown
new data source, CA Certificate.
> new data source, CA Certificate.

- .gitignore
- Makefile
- appgate/resource_appgate_administrative_role.go
- appgate/resource_appgate_administrative_role_test.go
- appgate/util.go
Updated Create, Read  & Update for Admin Roles, notice while using this resource, strange behavior during update when using multiple privileges and some logical errors with the usage of default_tags. This PR resolves those issues.
> Administrative role update

- appgate/config_test.go
- appgate/data_source_appgate_criteria_script.go
- appgate/data_source_appgate_entitlement_script.go
- appgate/data_source_appgate_global_settings.go
- appgate/provider.go
- appgate/resource_appgate_administrative_role.go
- appgate/resource_appgate_appliance.go
- appgate/resource_appgate_appliance_test.go
- appgate/resource_appgate_condition_test.go
- appgate/resource_appgate_global_settings.go
- appgate/resource_appgate_identity_provider_connector.go
- appgate/resource_appgate_identity_provider_local_database.go
- website/docs/d/global_settings.html.markdown
- website/docs/r/connector_identity_provider.markdown
- website/docs/r/global_settings.markdown
- website/docs/r/local_database_identity_provider.markdown
used [codespell](https://github.com/codespell-project/codespell) to resolve some of the common misspellings within the project.
> common misspellings

- Makefile
- appgate/resource_appgate_appliance.go
- appgate/resource_appgate_appliance_test.go
- website/docs/r/appliance.markdown
The API specification was wrong with the enum values.
> override_spa_mode Disabled is gone, omit to disable.

- appgate/resource_appgate_site.go
since both these attributes can only occur once, we can use TypeList to avoid computing hash value of the Set when we have compute values in the nested attributes. This fixes https://github.com/appgate/terraform-provider-appgatesdp/issues/121
acceptance test result `5.3.2-23587-release`
<details>
```
make testacc                                           
--- PASS: TestConfig (0.00s)
=== RUN …
```
> convert site.vpn and site.name_resolution to TypeList from TypeSet

- appgate/resource_appgate_appliance.go
This will prevent crash reported in #158 
Fixes #158
> Added nil check for state key

- appgate/data_source_appgate_appliance_seed.go
`data.appgatesdp_appliance seed`, dont return err if appliance is already activated.
I've manually tested this, could not figure out a suitable way to create an acceptance test for this case.
This PR fixes #164 
Acceptance test for 5.4.3-26106-release
<details>
```bash
> make testacc
=== RUN   TestConfigGetToken
=== RUN   TestConfigGetToken/test_before_5.4
2021/10/01 11:28:45 [DEBUG] Login OK
=== RUN   TestConfigGetToken/test_5.4_login
2021/10/01 11:28:45 [DEBUG] Login OK
=== RUN   TestConfigGetToken/invalid_client_version …
```
> appliance seed dont return err on activated appliances

- website/docs/r/appliance.markdown
Information on kinesis destination was missing from the docs so adding to help others out in the future.
> Adding details about Kinesis destination

- appgate/resource_appgate_site.go
Addressing #198
Aligning these values as "optional" instead of "required" with the documentation.
> Addressing site->vpn->route_via issues

- website/docs/r/admin_mfa_settings.markdown
- website/docs/r/administrative_role.markdown
- website/docs/r/appliance.markdown
- website/docs/r/appliance_customization.markdown
- website/docs/r/blacklist_user.markdown
- website/docs/r/client_connections.markdown
- website/docs/r/condition.markdown
- website/docs/r/connector_identity_provider.markdown
- website/docs/r/criteria_script.markdown
- website/docs/r/device_script.markdown
- website/docs/r/entitlement.markdown
- website/docs/r/entitlement_script.markdown
- website/docs/r/global_settings.markdown
- website/docs/r/ip_pool.markdown
- website/docs/r/ldap_certificate_identity_provider.markdown
- website/docs/r/ldap_identity_provider.markdown
- website/docs/r/license.markdown
- website/docs/r/local_database_identity_provider.markdown
- website/docs/r/local_user.markdown
- website/docs/r/mfa_provider.markdown
- website/docs/r/policy.markdown
- website/docs/r/radius_identity_provider.markdown
- website/docs/r/ringfence_rule.markdown
- website/docs/r/saml_identity_provider.markdown
- website/docs/r/site.markdown
- website/docs/r/trusted_certificate.markdown
include resource name in example of import, resolves https://github.com/appgate/terraform-provider-appgatesdp/issues/219
> include import resource name in examples

- .github/workflows/go.yml
Upgraded golang version in github action to resolve transitive dependencies builds
> Update gh action

- appgate/data_source_appgate_user_claim_script.go
- appgate/data_source_appgate_user_claim_script_test.go
- appgate/provider.go
- website/docs/d/user_claim_scripts.html.markdown
new data source for user claim script 
```hcl
data "appgate_user_claim_scripts" "default_user_claim_scripts" {
user_claim_scripts_name = "example"
}
```
branch built upon #242, part of #239
> Data source user claim script

- appgate/resource_appgate_appliance_test.go
- appgate/resource_appgate_global_settings.go
- appgate/resource_appgate_global_settings_test.go
added new attributes for spa_mode, spa_time_window_seconds, and collective_name for global settings
> V17 resource global settings

- appgate/resource_appgate_appliance.go
- appgate/resource_appgate_appliance_test.go
added new attribute for appliances version >= 6.0 `appliance.portal.sign_in_customization.auto_redirect`
> new attribute for >= 6.0 appliance.portal.sign_in_customization.auto_redirect

- appgate/resource_appgate_entitlement.go
- appgate/resource_appgate_entitlement_test.go
Updated resource entitlement to support new attribute, `risk_sensitivity` for version >= 6.0
> V17 resource entitlement

- appgate/resource_appgate_policy.go
- appgate/resource_appgate_policy_test.go
todo; depends on new client-profile, re-test
> V18 policy

- appgate/resource_appgate_entitlement.go
- appgate/resource_appgate_entitlement_test.go
Resolved typo in entitlement update method, which caused app_shortcuts not being able to update correctly. This PR fixes #295
> Issue 295/update entitlement app_shortcuts

- appgate/resource_appgate_local_user.go
this commit fixes https://github.com/appgate/terraform-provider-appgatesdp/issues/301
> read local user, handle 404

- appgate/provider.go
- appgate/resource_appgate_policy.go
- appgate/resource_appgate_policy_test.go
- appgate/resource_appgate_stop_policy.go
- appgate/resource_appgate_stop_policy_test.go
- website/docs/r/stop_policy.markdown
> Support Stop Policy

- appgate/resource_appgate_site_test.go
- website/docs/r/site.markdown
> Fix documentation for appgatesdp_site

- README.md
- appgate/resource_appgate_appliance.go
- website/docs/index.html.markdown
- website/docs/r/appliance.markdown
API/admin port updated from 444 to 8443
> API port changed from 444 to 8443

- appgate/resource_appgate_appliance.go
- appgate/resource_appgate_appliance_test.go
- website/docs/r/admin_mfa_settings.markdown
- website/docs/r/administrative_role.markdown
- website/docs/r/appliance.markdown
- website/docs/r/appliance_customization.markdown
- website/docs/r/blacklist_user.markdown
- website/docs/r/client_connections.markdown
- website/docs/r/condition.markdown
- website/docs/r/connector_identity_provider.markdown
- website/docs/r/criteria_script.markdown
- website/docs/r/device_script.markdown
- website/docs/r/entitlement.markdown
- website/docs/r/entitlement_script.markdown
- website/docs/r/global_settings.markdown
- website/docs/r/ip_pool.markdown
- website/docs/r/ldap_certificate_identity_provider.markdown
- website/docs/r/ldap_identity_provider.markdown
- website/docs/r/license.markdown
- website/docs/r/local_database_identity_provider.markdown
- website/docs/r/local_user.markdown
- website/docs/r/mfa_provider.markdown
- website/docs/r/oidc_identity_provider.markdown
- website/docs/r/radius_identity_provider.markdown
- website/docs/r/ringfence_rule.markdown
- website/docs/r/saml_identity_provider.markdown
- website/docs/r/site.markdown
- website/docs/r/trusted_certificate.markdown
* Add `appliance.gateway.suspended` to put Gateway n suspended mode or not. Suspended state will keep the existing Client connections but will reject new ones.
* Bunch of doc updates
> Add support to suspend gateway

- Makefile
- appgate/resource_appgate_blacklist_user_test.go
- appgate/resource_appgate_identity_provider_connector.go
- appgate/resource_appgate_identity_provider_ldap.go
- appgate/resource_appgate_identity_provider_ldap_certificate.go
- appgate/resource_appgate_identity_provider_local_database.go
- appgate/resource_appgate_identity_provider_oidc.go
- appgate/resource_appgate_identity_provider_radius.go
Port fix for #357 into release-6.5
> Wrong data type used for appgatesdp_oidc_identity_provider.claim_mappings #382

- Makefile
- appgate/resource_appgate_blacklist_user_test.go
- appgate/resource_appgate_identity_provider_connector.go
- appgate/resource_appgate_identity_provider_ldap.go
- appgate/resource_appgate_identity_provider_ldap_certificate.go
- appgate/resource_appgate_identity_provider_local_database.go
- appgate/resource_appgate_identity_provider_oidc.go
- appgate/resource_appgate_identity_provider_radius.go
Port fix for #357 into release-6.3
> Wrong data type used for appgatesdp_oidc_identity_provider.claim_mappings

- appgate/resource_appgate_site.go
- website/docs/r/site.markdown
Add the following missing fields:
- fallback_site
- geolocation
- local_site_detection
- use_for_nearest_site_selection
> Add missing fields for `appgatesdp_resource_Site

- appgate/config.go
- appgate/provider.go
- website/docs/guides/version_compatibility.markdown
- Add missing v22 API version
- Fix version compatibility documentation
> Add missing 6.5 API version 
